### ISSUE TITLE
Client.postThread() no longer seems to work.

### ISSUE THREAD

**Issue by Mastriel** [threadsjs/threads.js#12]
This issue was happening before the latest refactor happened.

Trying to use Client.postThread results in a response with an error code of 500 and this json body:
```json
{ message: 'Server has an unknown issue.', status: 'fail' }
```
I've quintuple checked my credentials to make sure they're correct, and it still results in this error occurring.

**Comment by ThisMe124** [comment]
Same here

**Comment by thisisdice** [comment]
Had no issues posting. some interesting details in the returned response below

`console.log
    {
      media: {
        taken_at: 1688823143,
        pk: redacted,
        id: 'redacted',
        device_timestamp: 0,
        media_type: 19,
        code: 'redacted',
        client_cache_key: 'redacted',
        filter_type: 0,
        can_viewer_reshare: true,
        caption: {
          pk: 'redacted',
          user_id: redacted,
          text: 'This Means HammerTime!',
          type: 1,
          created_at: 1688823143,
          created_at_utc: 1688823143,
          content_type: 'comment',
          status: 'Active',
          bit_flags: 0,
          did_report_as_spam: false,
          share_enabled: false,
          user: [Object],
          is_covered: false,
          is_ranked_comment: false,
          media_id: redacted,
          private_reply_status: 0
        },
        clips_tab_pinned_user_ids: [],
        comment_inform_treatment: {
          should_have_inform_treatment: false,
          text: '',
          url: null,
          action_type: null
        },
        fundraiser_tag: { has_standalone_fundraiser: false },
        sharing_friction_info: {
          should_have_sharing_friction: false,
          bloks_app_url: null,
          sharing_friction_payload: null
        },
        xpost_deny_reason: 'This post cannot be shared to Facebook.',
        caption_is_edited: false,
        original_media_has_visual_reply_media: false,
        like_and_view_counts_disabled: false,
        fb_user_tags: { in: [] },
        can_viewer_save: true,
        is_in_profile_grid: false,
        profile_grid_control_enabled: false,
        featured_products: [],
        is_comments_gif_composer_enabled: true,
        product_suggestions: [],
        user: {
          has_anonymous_profile_picture: false,
          all_media_count: 99,
          fan_club_info: [Object],
          fbid_v2: redacted,
          transparency_product_enabled: false,
          text_post_app_take_a_break_setting: 0,
          interop_messaging_user_fbid: redacted,
          show_insights_terms: false,
          allowed_commenter_type: 'any',
          is_unpublished: false,
          reel_auto_archive: 'on',
          can_boost_post: false,
          can_see_organic_insights: false,
          has_onboarded_to_text_post_app: true,
          text_post_app_joiner_number: redacted,
          pk: 7069455076,
          pk_id: '7069455076',
          username: 'redacted',
          full_name: 'redacted',
          is_private: false,
          profile_pic_id: 'redacted',
          profile_pic_url: 'redacted',
          account_badges: [],
          feed_post_reshare_disabled: false,
          show_account_transparency_details: true,
          third_party_downloads_enabled: 0
        },
        image_versions2: { candidates: [] },
        original_width: 612,
        original_height: 612,
        is_reshare_of_text_post_app_media_in_ig: false,
        comment_threading_enabled: false,
        max_num_visible_preview_comments: 2,
        has_more_comments: false,
        preview_comments: [],
        comment_count: 0,
        can_view_more_preview_comments: false,
        hide_view_all_comment_entrypoint: false,
        likers: [],
        shop_routing_user_id: null,
        can_see_insights_as_brand: false,
        is_organic_product_tagging_eligible: false,
        product_type: 'text_post',
        is_paid_partnership: false,
        music_metadata: null,
        deleted_reason: 0,
        organic_tracking_token: 'redacted',
        text_post_app_info: {
          is_post_unavailable: false,
          is_reply: false,
          reply_to_author: null,
          direct_reply_count: 0,
          self_thread_count: 0,
          reply_facepile_users: [],
          link_preview_attachment: null,
          can_reply: true,
          reply_control: 'everyone',
          hush_info: null,
          share_info: [Object]
        },
        integrity_review_decision: 'pending',
        ig_media_sharing_disabled: false,
        has_shared_to_fb: 0,
        is_unified_video: false,
        should_request_ads: false,
        is_visual_reply_commenter_notice_enabled: true,
        commerciality_status: 'not_commercial',
        explore_hide_comments: false,
        has_delayed_metadata: false
      },
      upload_id: 'None',
      status: 'ok'`

**Comment by elijah-wright** [comment]
noticing that these posts don't have an upload ID. this is something that I actually saw but couldn't figure out how to get. it's probably because there is no upload ID. I can try to figure that out.

**Comment by Mastriel** [comment]
Something else interesting that I noticed is that it only worked properly for the first post I had ever made to the account. After that, it didn't give me an error but it also didn't actually upload a new post. When I decided to delete the first post to see what that would do, I started getting the internal server error message.

**Comment by elijah-wright** [comment]
upload ID isn't something that's returned by any endpoint, which makes me think it could be a timestamp. if you leave a post hanging in Burp Suite and then post it five minutes later, it will return the correct date of when you sent it. but it's not a Unix timestamp. I'll try to figure out what it is.

**Comment by Mastriel** [comment]
Something else I was thinking is that it may have something to do with using different android ids for both logging in and sending the post, but I'm not sure how that could have resulted in it working the first time but not any subsequent times.

**Comment by elijah-wright** [comment]
Unix timestamps work for the upload ID. fix is coming in a sec.
