### ISSUE TITLE
is using this safe from ban / block?

### ISSUE THREAD

**Issue by azkadev** [threadsjs/threads.js#15]

**Comment by thisisdice** [comment]
No off course not!

**Comment by elijah-wright** [comment]
yes, you're making the exact same calls. the only issue you might have is that you might get ratelimited with some "unmapped IG error" which is what I'm facing right now.

**Comment by thisisdice** [comment]
Sorry what I meant is using any form of automation can create blocks! You need to use restraint to not abuse the endpoints. I’ve lost many IG accounts using similar methods
