### ISSUE TITLE
How are you going about finding endpoints.

### ISSUE THREAD

**Issue by olijeffers0n** [threadsjs/threads.js#2]
Hi there, Looks cool just wondered how you were finding these endpoints. I tried to proxy my phone but it seems they employ SSL pinning so had no luck. Let me know

**Comment by elijah-wright** [comment]
I only have access to the web endpoints. I experienced the same SSL pinning issues so it seems like someone will need to make a patched version.

**Comment by elijah-wright** [comment]
update: I have patched the threads app and obtained some endpoints. will work on this in the morning.

**Comment by elijah-wright** [comment]
moving this to #6
