### ISSUE TITLE
Error: Token is required.

### ISSUE THREAD

**Issue by soorooghadim** [threadsjs/threads.js#24]
Hi Problem 
Error : `Error: Token is required.`

**Comment by elijah-wright** [comment]
could you provide your code?

**Comment by thisisdice** [comment]
Check the readme 

That error comes from here:

`class Client extends EventEmitter {
	constructor({ token, userAgent, appId }) {
		super({ captureRejections: true });
		
		if (!token) {
			throw new Error("Token is required.");
		}`

**Comment by micheltucker** [comment]
It's because the demo code does not work as intended. Should be changed so that new Client only gets called afger the token is available.

```
const { getToken, Client } = require('./src/index.js');

(async () => {
  const token = await getToken('username', 'password');
  const client = new Client({ token });

  const user = await client.users.fetch('25025320');
  console.log(user);
})();
```

**Comment by elijah-wright** [comment]
thanks @micheltucker!
