### ISSUE TITLE
invalid token response

### ISSUE THREAD

**Issue by JastinXyz** [threadsjs/threads.js#26]
I doubt if everyone is experiencing the same thing or not? i can't get valid token when using getToken function. The response from the function is always the raw response from the API (with some being truncated due to "substrings" in some variables) as shown below.

![image](https://github.com/threadsjs/threads.js/assets/73673322/6b0dec6b-3354-4022-9983-b86b109340e4)

I think the issue is in the "end" variable
https://github.com/threadsjs/threads.js/blob/292df7d245497de65a6eff6e2c3704b5d7005cbe/src/index.js#L55

But I can fix it with the code below
```js
const pos = text.search("Bearer IGT:2:");
const sliced = text.substring(pos);
const token = sliced.substring(13, sliced.search(/\\\*?/gm));
return token;
```
Do I need to open a new pull request or is there another way to fix this problem?

**Comment by micheltucker** [comment]
I have the same issue. I was wondering why nobody has encountered that. Would just do a PR and see what @elijah-wright thinks.

**Comment by micheltucker** [comment]
> I doubt if everyone is experiencing the same thing or not? i can't get valid token when using getToken function. The response from the function is always the raw response from the API (with some being truncated due to "substrings" in some variables) as shown below.
> 
> ![image](https://user-images.githubusercontent.com/73673322/252131328-6b0dec6b-3354-4022-9983-b86b109340e4.png)
> 
> I think the issue is in the "end" variable
> 
> https://github.com/threadsjs/threads.js/blob/292df7d245497de65a6eff6e2c3704b5d7005cbe/src/index.js#L55
> 
> But I can fix it with the code below
> 
> ```js
> const pos = text.search("Bearer IGT:2:");
> const sliced = text.substring(pos);
> const token = sliced.substring(13, sliced.search(/\\\*?/gm));
> return token;
> ```
> 
> Do I need to open a new pull request or is there another way to fix this problem?

Also tried your solution and it works for me.

**Comment by JastinXyz** [comment]
> I have the same issue. I was wondering why nobody has encountered that. Would just do a PR and see what @elijah-wright thinks.

ok I would open a new PR

**Comment by sooluh** [comment]
Actually, I have a fixed parser, but I haven't finished implementing the 2FA method yet, so I will make a pull request with 2FA as soon as possible.
