### ISSUE TITLE
`getToken` should be asynchronous

### ISSUE THREAD

**Issue by esau-morais** [threadsjs/threads.js#30]
`'await' has no effect on the type of this expression.ts(80007)`

![image](https://github.com/threadsjs/threads.js/assets/55207584/bfd84efc-594f-4501-b3b4-fe06ccefe4ef)

[
type](https://github.com/threadsjs/threads.js/blob/main/typings/index.d.ts#L51) correctly

**Comment by elijah-wright** [comment]
fixed
