### ISSUE TITLE
instagram saying suspicious login and changing password always 

### ISSUE THREAD

**Issue by serhaterfidan** [threadsjs/threads.js#31]
when I call 
const token = await getToken(username, password); 

token is getting invalid here but logged in instagram succesfull but as suspicious login and instagram force change password how can we this safe call and also handle token issue

**Comment by elijah-wright** [comment]
this isn't something I can do anything about, it's just Instagram being suspicious of a new device. just save your token and use it for later.

**Comment by elijah-wright** [comment]
I'm going to close this now, reopen it if you still need help

**Comment by serhaterfidan** [comment]
> this isn't something I can do anything about, it's just Instagram being suspicious of a new device. just save your token and use it for later.

but any user request this library as login should they save them tokens it's not solution every user login has this problem not just for me
