### ISSUE TITLE
GET own user

### ISSUE THREAD

**Issue by mazenkourouche** [threadsjs/threads.js#32]
I haven't been able to find a method to get the own user's ID. Is this possible?

**Comment by elijah-wright** [comment]
there's an endpoint for this i believe but unfortunately i can't check what it is right now. i'll try to find it

**Comment by stevenlafl** [comment]
+1

**Comment by elijah-wright** [comment]
the userid field is the poster's. there are two "ids" in posts, and they both contain the same id but one of them has to include an underscore and then the id of the user who posted it. for some reason, that endpoint needs to have the second one.

I'm having issues with my setup to get endpoints right now, so it'll be a bit but it is most likely possible, just to let you know

**Comment by mazenkourouche** [comment]
I played around and found using ID 1 works for posting to my feed. But doesnt hat mean passing in someone else's ID will allow you to post to someone else's feed?

**Comment by elijah-wright** [comment]
no, the ids are locked to the user.

I checked the endpoints and found that the id is inherent, so in short, it's not possible to get an id from a token like that. I'll keep this open in case anyone has something new to report

**Comment by sooluh** [comment]
I have created a utility to parse the bloks response when getting a token, and there we can retrieve the user ID (often referred to as pk or pk_id in the response). Please check [#L56](https://github.com/threadsjs/threads.js/blob/main/src/index.js#L56) for the variable "bloks" and simply access `bloks.login_response.logged_in_user.pk`. The pk is of type number, and pk_id is of type string. I hope this helps.
