### ISSUE TITLE
Suggestions for this project

### ISSUE THREAD

**Issue by sooluh** [threadsjs/threads.js#34]
I have a few suggestions for this project. I don't think it's necessary to separate the getToken method from the Client class to make it easier to access. We need the user ID and the token, so perhaps we should consider changing the class name to "Threads" or something similar, instead of "Client". The constructor function should accept an object containing the username and password, where we can obtain the token and user ID, and finally store them as class properties.

If possible, it would be good to save the token and user ID in a file. We could customize the storage path through an object when creating the class, in the constructor. Then, if the file already exists, we can simply use the existing token and user ID, eliminating the need to request a new token.

I would like to help and create a pull request, but unfortunately, I don't have the time for it.

**Comment by thisisdice** [comment]
Sessions are keys for the longevity of accounts. But there are a lot of moving parts calls in the calls back and fourth

**Comment by thisisdice** [comment]
‘’’
const threadsAPI = new threadsAPI({
  token: //Optional token
  session: 'example-session', // Optional: Provide a session identifier
  proxy: 'http://example-proxy.com', // Optional: Provide a proxy URL
});

async function exampleUsage() {
  try {
    await threadsAPI.init('username', 'password');

    const user = await threadsAPI.getUser('123456789');
    console.log('User:', user);

    // ... Other API methods
  } catch (error) {
    console.error('Error:', error);
  }
}

exampleUsage();
,,,
‘’’

constructor(options: threadsAPIOptions = {}) {
    this.session = options.session;
    this.proxy = options.proxy;
    this.deviceId = options.deviceId || `android-${(Math.random() * 1e24).toString(36)}`;
  }

  public async init(username: string, password: string): Promise<void> {
    if (this.session) {
      // Load session if available
      this.loadSession();
      return;
    }

   
    this.token = await this.getToken(username, password);

    // Save session
    this.saveSession();
  }

‘’’

‘’’
private saveSession(): void {
    if (this.session) {
      // Save session, device ID, and other necessary data to storage
      // Example: localStorage.setItem('instagramSession', JSON.stringify({ session: this.session, deviceId: this.deviceId }));
    }
  }

  private loadSession(): void {
    if (this.session) {
      // Load session, device ID, and other necessary data from storage
      // Example: const sessionData = localStorage.getItem('instagramSession');
      //          if (sessionData) {
      //            const { session, deviceId } = JSON.parse(sessionData);
      //            this.session = session;
      //            this.deviceId = deviceId;
      //          }
    }
  } ,,,

**Comment by sooluh** [comment]
> idk about the other stuff but the token is already saved in the constructor so saving it in a file is kind of useless.

What I mean is, in some cases, using this as a bot (including myself), I don't want to deal with the generated tokens. All I want to do is create a class and input the username and password. To minimize the request for token generation, it's better to store it in a file rather than waiting for a token every time the bot is run. This is especially true if I enable 2FA, as it would take even more time.

This is just my opinion.

**Comment by sooluh** [comment]
Ah, I apologize for the misunderstanding. So, the purpose of this project is to create an unofficial web client, not for bot purposes. Okay, I'm sorry about that. Maybe we need to create a separate repository for it.

**Comment by micheltucker** [comment]
> Ah, I apologize for the misunderstanding. So, the purpose of this project is to create an unofficial web client, not for bot purposes. Okay, I'm sorry about that. Maybe we need to create a separate repository for it.

I think either would be interesting. Would be sweet to do a fork and try a more bot-driven approach. I am more on the web interface side, but would love to learn.

**Comment by elijah-wright** [comment]
i'm making this to serve both use cases. i have a web client myself that supports logging in through generating a token so it's definitely possible to do both.

here, i thought about this last night. would a login function that generates a token inside the client constructor work for everyone?

**Comment by sooluh** [comment]
We can create a method in the class to get it from the set property

**Comment by sooluh** [comment]
We can create a method in the class to get it from the set property
