### ISSUE TITLE
getToken issue

### ISSUE THREAD

**Issue by serhaterfidan** [threadsjs/threads.js#36]
token is getting invaild here how can I pass this part 

const token = await getToken(username, password);

instagram logged successful but token is getting null here

**Comment by sooluh** [comment]
is it true that the token variable is null? i used three accounts with 2FA and two accounts without 2FA, and it all worked :)

**Comment by serhaterfidan** [comment]
instagram logged in succesful but token is getting null I am printing token on console

**Comment by serhaterfidan** [comment]
can you give me your email for discussions I have questions

**Comment by serhaterfidan** [comment]
TypeError: fetch is not a function
    at getToken (/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/index.js:54:25)
    at /Users/serhaterfidan/Desktop/threadsapi/server.js:20:25
    at Layer.handle [as handle_request] (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/layer.js:95:5)
    at /Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:284:15
    at param (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:421:3)

**Comment by sooluh** [comment]
try to delete node_modules and reinstall using your package manager

**Comment by serhaterfidan** [comment]
I tried many times remove or install again but still same error

**Comment by elijah-wright** [comment]
what is your node version

**Comment by serhaterfidan** [comment]
v14.21.3

**Comment by serhaterfidan** [comment]
I update node.js version to v18.16.1 and error changed like this

TypeError: getToken is not a function
    at /Users/serhaterfidan/Desktop/threadsapi/server.js:15:25
    at Layer.handle [as handle_request] (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/layer.js:95:5)
    at /Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:284:15
    at param (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:421:3)
    at next (/Users/serhaterfidan/Desktop/threadsapi/node_modules/express/lib/router/index.js:280:10)

**Comment by elijah-wright** [comment]
yeah, getToken got removed in 1.6.1 which got pushed this morning. try using something like this:

```
(async () => {
	const client = new Client();
	await client.login('username', 'password');
})();
```

**Comment by elijah-wright** [comment]
I'll take a look at it

**Comment by elijah-wright** [comment]
ah, ok, you need to use `new Client({});`, not `new Client();`. i'll fix that in the readme, thanks

**Comment by elijah-wright** [comment]
@sooluh you know more about this bloks stuff more than me lol. if parseBloksResponse is wrong, could mean that the username/password is wrong.

**Comment by serhaterfidan** [comment]
username and password is true I checked on instagram

**Comment by sooluh** [comment]
I'll try again, soon.

**Comment by elijah-wright** [comment]
you have to pass an empty object into the client constructor.

**Comment by serhaterfidan** [comment]
> if you can, edit the file at `/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/index.js` and put "console.log(bloks.login_response)" above it. is there anything?

undefined printed

**Comment by serhaterfidan** [comment]
> > if you can, edit the file at `/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/index.js` and put "console.log(bloks.login_response)" above it. is there anything?
> 
> console logged undefined

**Comment by elijah-wright** [comment]
try logging bloks, it's probably giving you an error

**Comment by serhaterfidan** [comment]
console logged [object Object]

**Comment by sooluh** [comment]
It's just a placement error. Those who use 2FA cannot directly retrieve logged_in_user.pk. This only works for accounts without 2FA.

**Comment by elijah-wright** [comment]
should be fixed in 1.6.3

**Comment by serhaterfidan** [comment]
TypeError: client.getToken is not a function
    at /Users/serhaterfidan/Desktop/threadsapi/server.js:18:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by serhaterfidan** [comment]
this my code 

try {
    const { username, password } = req.query;
    const userId = req.params.userId;

    const client = new Client({});
    await client.login(username, password);

    const token = client.getToken(); // Retrieve the token from the Client instance
    if (!token) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    const user = await client.users.fetch(userId);
    res.json(user);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'An error occurred during computation' });
  }

**Comment by sooluh** [comment]
@elijah-wright, I have just submitted a pull request. I have fixed it so that even when the Client class is initialized without an empty object, it can still retrieve the userId correctly for both accounts with and without 2FA enabled.

**Comment by sooluh** [comment]
@serhaterfidan Please try to update to the latest version available.

**Comment by elijah-wright** [comment]
could you `console.log(client)`?

**Comment by serhaterfidan** [comment]
Client {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  token: null,
  userAgent: 'Barcelona 289.0.0.77.109 Android',
  appId: '238260118697367',
  androidId: '3hp0if058dk00000',
  userId: null,
  rest: RESTManager {},
  users: UserManager {},
  posts: PostManager {},
  feeds: FeedManager {},
  [Symbol(kCapture)]: true
}
TypeError: Cannot read properties of undefined (reading 'logged_in_user')
    at Client.login (/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/index.js:135:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/serhaterfidan/Desktop/threadsapi/server.js:17:5

**Comment by sooluh** [comment]
What you are currently testing, is it using 2FA or not?

**Comment by elijah-wright** [comment]
try 1.6.5

**Comment by serhaterfidan** [comment]
I don't have 2FA on my account

**Comment by sooluh** [comment]
> try 1.6.5

I think that code will remove the userId, does it mean not everyone has a userId? This is very strange.

**Comment by serhaterfidan** [comment]
I updated but error is same 

Client {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  token: null,
  userAgent: 'Barcelona 289.0.0.77.109 Android',
  appId: '238260118697367',
  androidId: 'q3icvec75r40000',
  userId: null,
  rest: RESTManager {},
  users: UserManager {},
  posts: PostManager {},
  feeds: FeedManager {},
  [Symbol(kCapture)]: true
}
TypeError: Cannot read properties of undefined (reading 'logged_in_user')
    at Client.login (/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/index.js:135:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/serhaterfidan/Desktop/threadsapi/server.js:17:5

**Comment by serhaterfidan** [comment]
do you have any test account for test

**Comment by sooluh** [comment]
Damn, your account has been hit with a checkpoint. Please check your Instagram application, you may be required to change your password.

**Comment by serhaterfidan** [comment]
yes instagram wants change password after request always

**Comment by sooluh** [comment]
> yes instagram wants change password after request always

Certainly, because Instagram detects unusual activities on your account, that's why it happened.

**Comment by stevenlafl** [comment]
> Damn, your account has been hit with a checkpoint. Please check your Instagram application, you may be required to change your password.

Well, that's a great case to at least handle. Can the error be made to go all the way through to the response at client.login() ? I would definitely expect that kind of behavior so the frontend can display it (especially for my use case)

**Comment by serhaterfidan** [comment]
I can test if you find a solution notify me

**Comment by serhaterfidan** [comment]
when I changed password token got true after request

**Comment by sooluh** [comment]
> when I changed password token got true after request

Of course, because there is nothing wrong. This is just a security measure implemented by Instagram when there is suspicious activity.

**Comment by elijah-wright** [comment]
i had the same problem as serhat and lol it's a tricky one. i ended up just switching to another account. idk if my old one is still blocked or anything. fwiw, this is also happening to people who don't even use the API because they're switching between two accounts really quickly

feel free to make a pr 👍

**Comment by sooluh** [comment]
> feel free to make a pr 👍

At very least, we can only perform validation checks when an account is with a checkpoint.

**Comment by birobirobiro** [comment]
Same problem here:

```bash
/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/util/Bloks.js:30
    const sanitized = JSON.parse(JSON.parse(Object.values(tree)[0]['#'].match(/\"\{.*\}\"/)[0]));
                                                                                           ^

TypeError: Cannot read properties of null (reading '0')
    at parseBloksResponse (/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/util/Bloks.js:30:92)
    at Client.login (/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/index.js:75:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/birobirobiro/Developer/side-projects/threadsjs/index.js:8:3

Node.js v18.16.0
```

**Comment by serhaterfidan** [comment]
okay I got token but I have a problem here 

const user = await client.users.fetch(userId);

{
    "message": "Target user not found",
    "status": "fail"
}

**Comment by elijah-wright** [comment]
is userId a string with a valid userId?

**Comment by serhaterfidan** [comment]
> is userId a string with a valid userId?

Yes but I realized my threads id not showing on my profile on instagram on my test account but real account it's showing

**Comment by serhaterfidan** [comment]
it's showing now on my instagram profile but still

{ message: 'Target user not found', status: 'fail' }

**Comment by sooluh** [comment]
What when the userId is console.log?

**Comment by serhaterfidan** [comment]
> What when the userId is console.log?

97784297

**Comment by birobirobiro** [comment]
> @birobirobiro, can you open `/Users/birobirobiro/Developer/side-projects/threadsjs/node/@threadsjs/threads.js/src/util/Bloks.js` and add `console.log(tree);` above line 30?

```js
function parseBloksResponse(text) {
    const { tree } = JSON.parse(text).layout.bloks_payload;
    const sanitized = JSON.parse(JSON.parse(Object.values(tree)[0]['#'].match(/\"\{.*\}\"/)[0]));

    console.log(`tree: ${JSON.stringify(tree)}`);

    const json = parseNestedJson(sanitized);

    console.log(`sanitized: ${JSON.stringify(sanitized)}`);
    return json;
}
```

```bash
❯ yarn start
yarn run v1.22.19
$ node index.js
/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/util/Bloks.js:30
    const sanitized = JSON.parse(JSON.parse(Object.values(tree)[0]['#'].match(/\"\{.*\}\"/)[0]));
                                                                                           ^

TypeError: Cannot read properties of null (reading '0')
    at parseBloksResponse (/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/util/Bloks.js:30:92)
    at Client.login (/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/index.js:75:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/birobirobiro/Developer/side-projects/threadsjs/index.js:9:3

Node.js v18.16.0
error Command failed with exit code 1.
```

**Comment by sooluh** [comment]
> 97784297

From my account, the response is the same. Can I know the username

**Comment by birobirobiro** [comment]
> Try placing console.log(tree) below tree variable.
> 
> ```js
> function parseBloksResponse(text) {
>     const { tree } = JSON.parse(text).layout.bloks_payload;
>     console.log(`tree: ${JSON.stringify(tree)}`);
>     const sanitized = JSON.parse(JSON.parse(Object.values(tree)[0]['#'].match(/\"\{.*\}\"/)[0]));
>     const json = parseNestedJson(sanitized);
>     return json;
> }
> ```

```bash
tree: {"㐟":{"#":" (bk.action.core.TakeLast, (bk.action.core.TakeLast, (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \"login_type\", \"login_source\"), (bk.action.array.Make, \"Password\", \"Login\"))), (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \"end_point\"), (bk.action.array.Make, \"generic_error_dialog\"))), (bk.action.qpl.MarkerEndV2, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.i32.Const, 87), (bk.action.tree.Make, (bk.action.i32.Const, 13704)))), null, (bk.action.core.TakeLast, (bk.action.i32.Const, 1), (ig.action.cdsdialog.OpenDialog, (bk.action.tree.Make, (bk.action.i32.Const, 13799), (bk.action.i32.Const, 40), \"Incorrect Password\", (bk.action.i32.Const, 35), \"The password you entered is incorrect. Please try again.\", (bk.action.i32.Const, 36), (bk.action.tree.Make, (bk.action.i32.Const, 13800), (bk.action.i32.Const, 36), \"OK\", (bk.action.i32.Const, 35), (bk.action.core.FuncConst, (bk.action.logging.LogEvent, \"caa_login_client_events_ig\", \"\", (bk.action.map.Make, (bk.action.array.Make, \"core\", \"login_params\"), (bk.action.array.Make, (bk.action.map.Make, (bk.action.array.Make, \"event\", \"event_category\", \"event_flow\", \"event_request_id\", \"event_step\", \"is_dark_mode\", \"exception_code\", \"exception_message\", \"exception_type\", \"extra_client_data\", \"logged_out_identifier\", \"logged_in_identifier\", \"waterfall_id\"), (bk.action.array.Make, \"login_error_dialog_ok_clicked\", \"login_home_page_interaction\", \"login_manual\", \"a24f940c-c6df-465a-befa-223573b3879a\", \"home_page\", (ig.action.IsDarkModeEnabled), (bk.action.i32.Const, 0), \"\", \"\", (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make)), \"\", \"\", \"16baceaa-07a1-483e-b112-09a9638fc775\")), (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make))))))), (bk.action.i32.Const, 42), (bk.action.i32.Const, 0)), (bk.action.tree.Make, (bk.action.i32.Const, 13808))), (bk.action.core.TakeLast, (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \"login_type\", \"login_source\"), (bk.action.array.Make, \"Password\", \"Login\"))), (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \"end_point\"), (bk.action.array.Make, \"generic_error_dialog\"))), (bk.action.qpl.MarkerEndV2, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.i32.Const, 87), (bk.action.tree.Make, (bk.action.i32.Const, 13704)))), (bk.action.map.Make, (bk.action.array.Make, \"should_dismiss_loading\"), (bk.action.array.Make, (bk.action.bool.Const, false)))))"}}
/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/util/Bloks.js:31
    const sanitized = JSON.parse(JSON.parse(Object.values(tree)[0]['#'].match(/\"\{.*\}\"/)[0]));
                                                                                           ^

TypeError: Cannot read properties of null (reading '0')
    at parseBloksResponse (/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/util/Bloks.js:31:92)
    at Client.login (/Users/birobirobiro/Developer/side-projects/threadsjs/node_modules/@threadsjs/threads.js/src/index.js:75:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/birobirobiro/Developer/side-projects/threadsjs/index.js:9:3

Node.js v18.16.0
error Command failed with exit code 1.
```

**Comment by serhaterfidan** [comment]
> > 97784297
> 
> From my account, the response is the same. Can I know the username

Client user id and Threads user id is different I didn't find any related info in Client response for Threads

**Comment by serhaterfidan** [comment]
wait I found text_post_app_joiner_number: 97784297,

**Comment by sooluh** [comment]
@birobirobiro You entered the wrong password, buddy. Phew, it seems like we to validate this again.

**Comment by serhaterfidan** [comment]
Client.users not getting Threads user it's getting Instagram user info

**Comment by serhaterfidan** [comment]
Sorry I got it now okay user id is already in the Client object I mixed it Threads id issue resolved thanks guys

**Comment by birobirobiro** [comment]
> 

Is that correct, I'm using 2FA could this be impacting?

**Comment by sooluh** [comment]
2FA doesn't affect anything, everything has been handled. However, we't handled the incorrect password error yet. In the console.log output you sent, it states that the password is incorrect.

**Comment by birobirobiro** [comment]
> 2FA doesn't affect anything, everything has been handled. However, we't handled the incorrect password error yet. In the console.log output you sent, it states that the password is incorrect.

I put an example token and password to show you how I'm doing it in the code, is that correct?

```js
const { Client } = require('@threadsjs/threads.js');

(async () => {
  const client = new Client({
    token: '123456',
  }
  );
  // You can also specify a token: const client = new Client({ token: 'token' });
  await client.login('birobirobiro', '123456;');

  await client.users.fetch('30626776').then(user => {
    console.log(user);
  });
})();
```

**Comment by sooluh** [comment]
In client declaration, you don't need to add an object containing the token. Just use `const client = new Client({});` and the rest is fine. However, the error occurs because the account password is incorrect.

**Comment by birobirobiro** [comment]
> In client declaration, you don't need to add an object containing the token. Just use `const client = new Client({});` and the rest is fine. However, the error occurs because the account password is incorrect.

I just logged in through the browser using the login and password, the same ones I'm passing in the code and I logged in normally

**Comment by sooluh** [comment]
@elijah-wright Is there no parser outside that can parse the Bloks framework used by Threads and Instagram Lite? This is really stressing me out haha.

**Comment by elijah-wright** [comment]
not that i know of

**Comment by birobirobiro** [comment]
> @elijah-wright Is there no parser outside that can parse the Bloks framework used by Threads and Instagram Lite? This is really stressing me out haha.
> 
> Using regex (like in the initial release) is very limited because we only get the, while there is a JSON there that we can all of its contents.

I tested with another account, even with 2FA enabled and it worked. I think my birobirobiro account must have some blocking on the Instagram API side.

I found this issue here that might help you resolve this as well, it seems like it's a common issue. It's not just a lock

https://github.com/jlobos/instagram-web-api/issues/302#issuecomment-1542546686

**Comment by serhaterfidan** [comment]
guys token and user coming success on localhost but coming null on Heroku why is that

**Comment by serhaterfidan** [comment]
solved :)

**Comment by sooluh** [comment]
Hi @elijah-wright, sorry for reopening the conversation on this closed issue, but I thought you might need this. I just created a utility to parse responses from the Meta's Bloks framework. I believe it's safer (at least for now, there might be new cases in the future or not). In there, I return isFailed if the username or password is incorrect, isTwoFactor if the account has enabled 2FA, and of course, isSuccess. There is also data that contains an object that can be used to retrieve the JSON response. I hope this helps!

https://github.com/sooluh/bloks-parser
