### ISSUE TITLE
Can we use this without Node JS? Like in just React JS

### ISSUE THREAD

**Issue by sulaimanwebdev** [threadsjs/threads.js#40]
Can we use this without Node JS? Like in just React JS

**Comment by thisisdice** [comment]
Check out https://github.com/stevenlafl/threads-web-client

**Comment by micheltucker** [comment]
I mean that is NextJS, which is NodeJS. Why would you want to use it in vanilla ReactJS?

**Comment by sulaimanwebdev** [comment]
> I mean that is NextJS, which is NodeJS. Why would you want to use it in vanilla ReactJS?

I'm just curious if we could you use it without backend?

**Comment by sulaimanwebdev** [comment]
> Check out https://github.com/stevenlafl/threads-web-client

Bro you did amazing job. How do Threads JS really works does it scrapes data?

**Comment by elijah-wright** [comment]
it's just endpoints, no scraping

**Comment by sulaimanwebdev** [comment]
How is this possible without official Instagram/Threads API? Can you please the logic?

**Comment by elijah-wright** [comment]
I just monitored the traffic from the app

**Comment by elijah-wright** [comment]
closing
