### ISSUE TITLE
how can I make login with Instagram Auth 

### ISSUE THREAD

**Issue by serhaterfidan** [threadsjs/threads.js#41]
how can I make login without username and password and just use with Instagram Auth and token for Threads Client

**Comment by elijah-wright** [comment]
not possible afaik. you don't need to log in with your username and password, but you need those to generate a token that can be used to log in without one

**Comment by serhaterfidan** [comment]
token and user coming success on localhost but coming null on Heroku why is that

**Comment by serhaterfidan** [comment]
solved :)
