### ISSUE TITLE
Method IDs (post and user)

### ISSUE THREAD

**Issue by mazenkourouche** [threadsjs/threads.js#44]
Not sure if this has been answered yet but which IDs should be used for user and post?

I'm getting 'Unknown server error' when performing a reply.

Im using the post.id and user.pk_id for that post. Should the user ID be my ID? (if so, have we found a way to get that ID from the token)?

**Comment by elijah-wright** [comment]
the user ID needs to be the the poster's. so if instagram makes a post, it would be the post ID and then the user ID of instagram

**Comment by mazenkourouche** [comment]
Sorry just trying to work my head around why I'm getting the "unknown server error". So assuming this is the post I want to reply to:

`"items": [
    {
      "thread_items": [
        {
          "post": {
            "pk": 3144129357602005500,
            "id": "3144129357602005392_1468330069",
            "text_post_app_info": {
              ...
            },
            "caption": {
              "pk": "17923171223651751",
              "user_id": 1468330069,
              "text": "why does tiredness on the couch not follow me to the bed",
              ...
              "user": {
                "pk": 1468330069,
                "pk_id": "1468330069",
                "username": "nugget",
                "full_name": "Nugget",
                "is_private": false,
                "is_verified": false,
                ...
              },
              "is_covered": false,
              "is_ranked_comment": false,
              "media_id": 3144129357602005500,
              "private_reply_status": 0
            },
            ...
            "top_likers": ["iy0017"],
            "user": {
              "pk": 1468330069,
              "pk_id": "1468330069",
              "username": "nugget",
              "full_name": "Nugget",
              "is_private": false,
              "is_verified": false,
              "profile_pic_id": "3140521191102418822_1468330069",
              "friendship_status": {
                "following": false,
                "followed_by": false,
                ...
              },
              "has_anonymous_profile_picture": false,
              "has_onboarded_to_text_post_app": true,
              "account_badges": []
            },
          },
        }
      ],
      "header": null,
      "thread_type": "thread",
      "show_create_reply_cta": false,
      "id": 3144129357602005500,
      "view_state_item_type": 132,
      "posts": [
        {
          "pk": 3144129357602005500,
          "id": "3144129357602005392_1468330069",
          },
          "caption": {
            "pk": "17923171223651751",
            "user_id": 1468330069,
            "text": "why does tiredness on the couch not follow me to the bed",
            "type": 1,
            "share_enabled": false,
            "user": {
              "pk": 1468330069,
              "pk_id": "1468330069",
              "username": "nugget",
              "full_name": "Nugget",
              "profile_pic_id": "3140521191102418822_1468330069",
              "profile_pic_url": "https://instagram.fsyd11-1.fna.fbcdn.net/v/t51.2885-19/358014596_773656351107850_338257440156264279_n.jpg?stp=dst-jpg_s150x150&_nc_ht=instagram.fsyd11-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=t3aF5PMZBScAX9KkfIh&edm=AJ1VKAgBAAAA&ccb=7-5&oh=00_AfBIxzmHDcO9xZao3rDGPTUpuqztEACmosz80KK4avPWnA&oe=64B1F019&_nc_sid=69b717",
              "fbid_v2": "17841401262092942",
              "has_onboarded_to_text_post_app": true
            },
            "is_covered": false,
            "is_ranked_comment": false,
            "media_id": 3144129357602005500,
            "private_reply_status": 0
          },
          "original_width": 612,
          "original_height": 612,
          "user": {
            "pk": 1468330069,
            "pk_id": "1468330069",
            "username": "nugget",
            "full_name": "Nugget",
            "is_private": false,
            },
            "has_anonymous_profile_picture": false,
            "has_onboarded_to_text_post_app": true,
            "account_badges": []
          },
        }
      ]
    },`
    
    the post ID would be '"id": "3144129357602005392_1468330069" and the user ID would be 1468330069?

**Comment by elijah-wright** [comment]
here's what I tried:
```
await client.posts.fetch('3144129357602005500', '1468330069').then(post => {
	console.log(post);
});
```
and I got something about being unable to read the post

**Comment by elijah-wright** [comment]
closing, I assume this is resolved
