### ISSUE TITLE
Remove my followings

### ISSUE THREAD

**Issue by serhaterfidan** [threadsjs/threads.js#45]
Can this feature develop for user followings?

**Comment by micheltucker** [comment]
What does that mean? You want to remove some of your followers?

**Comment by stevenlafl** [comment]
To 'unfollow' it's:

```js
async follow(user) {
		return await this.request(`/api/v1/friendships/destroy/${user}/`, {
			method: 'POST',
		});
	}
```

So if using the Rest client:
```js
// However you're instantiating your client
// const client = new Client({ token });

let user = '<user id>';
payload = await client.rest.(`/api/v1/friendships/destroy/${user}/`, {
	method: 'POST',
});
```

Can you try this for me and see how it goes?

**Comment by serhaterfidan** [comment]
unfollow not working

**Comment by stevenlafl** [comment]
Please show some code for what you're using and provide the ID (and handle, so I can verify the user's ID independently). Also can you show the output you're getting back?

**Comment by serhaterfidan** [comment]
you didn't update npm methods not coming
