### ISSUE TITLE
I am getting this error on 1.7.0

### ISSUE THREAD

**Issue by serhaterfidan** [threadsjs/threads.js#55]
{
    "message": "challenge_required",
    "challenge": {
        "url": "https://www.instagram.com/accounts/suspended/",
        "api_path": "/challenge/",
        "hide_webview_header": true,
        "lock": true,
        "logout": false,
        "native_flow": true,
        "flow_render_type": 0
    },
    "status": "fail"
}

**Comment by elijah-wright** [comment]
can you log in on your phone?

**Comment by serhaterfidan** [comment]
no account suspended

**Comment by JastinXyz** [comment]
> no account suspended

just create a new account, suspended account can't be used...

**Comment by elijah-wright** [comment]
alr, I'm going to close this now

**Comment by teradevs** [comment]
> no account suspended

Did this happen after using this package?

**Comment by serhaterfidan** [comment]
TypeError: Cannot read properties of null (reading '0')
at parseBloksResponse (/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/util/Bloks.js:30:89)
at Client.login (/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/index.js:75:17)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /Users/serhaterfidan/Desktop/threadsapi/server.js:17:5

**Comment by serhaterfidan** [comment]
> > no account suspended
> 
> Did this happen after using this package?

yes

**Comment by elijah-wright** [comment]
welp, I was also just hit with this. tbh, idk what to do. only thing you can really do is cave in and submit a photo of your face, which I don't trust meta with that stuff so

it's not an issue with the package, it's just what you're doing with it. if you're making a bunch of suspicious requests, you're prob gonna get suspended
