### ISSUE TITLE
"login_required": User getting logged out after a few requests

### ISSUE THREAD

**Issue by mazenkourouche** [threadsjs/threads.js#57]
When you perform a few requests, you get logged out of the system with 

```
{
    "message": "login_required",
    "error_title": "You've Been Logged Out",
    "error_body": "Please log back in.",
    "logout_reason": 8,
    "status": "fail"
}
```

**Comment by soorooghadim** [comment]
I Have This Problem Too

```
{
    "message": "login_required",
    "error_title": "You've Been Logged Out",
    "error_body": "Please log back in.",
    "logout_reason": 8,
    "status": "fail"
}
```

**Comment by stevenlafl** [comment]
You should go here

https://accountscenter.instagram.com/password_and_security/

And hit your user account. Then press "unrecognized logins" and say "This was me" on each one.

**Comment by mazenkourouche** [comment]
@stevenlafl have you had the issue of getting "challenge_required" response? had it happen to two accounts now

**Comment by stevenlafl** [comment]
Are those accounts 2FA?

**Comment by stevenlafl** [comment]
@elijah-wright I am now getting this. I know it's unrelated to this library. What I am curious about is if this happened to you before you got suspended? I saw it logged me out of all my other devices, too. I'm wondering if maybe we should update the app version in the API. No idea what would solve it.

**Comment by elijah-wright** [comment]
it was kind of random, and then it stopped. last time I got it was when I published my web client and then I had to approve the request on my phone because Vercel's servers are in Virginia. I'll look at this in the morning

**Comment by elijah-wright** [comment]
just updated the app ID, see if that works

**Comment by elijah-wright** [comment]
no longer applicable in v2
