### ISSUE TITLE
endpoints discussion

### ISSUE THREAD

**Issue by elijah-wright** [threadsjs/threads.js#6]
the endpoints for threads are under `i.instagram.com`. endpoints I have found so far:
- [ ] `/api/v1/warning/check_offensive_multi_text/` - checks how offensive or sexual a post is. doesn't seem to do anything.
- [x] `/api/v1/media/configure_text_only_post/` - also don't know what this does but it takes a signed body
- [x] `/api/v1/users/USERID/info` - this one is quite interesting, it's equivalent to the endpoint in `getUser` but it's not authenticated. you need to pass a specialized user agent starting with "Barcelona", ending with "Android", and some version in the middle.
- [x] `/api/v1/text_feed/USERID/profile` - gets a user feed.
- [x] `/api/v1/users/search/` - explains itself pretty well, pass the q and count query strings. there's a timezone offset in there but idk what that does. needs authentication, haven't quite figured this one out yet
- [x] `/api/v1/text_feed/recommended_users/` - recommended users, needs auth

will continue in the morning, promising stuff. hopefully someone will crack auth by then

**Comment by micheltucker** [comment]
Could be possible that one needs Instagram's auth permissions for this. Found this discussion from back then: https://stackoverflow.com/questions/46573777/how-to-retrieve-instagram-username-from-user-id

**Comment by elijah-wright** [comment]
the text_feed endpoints seem to be the most important ones to write down, thanks @micheltucker

**Comment by JastinXyz** [comment]
@elijah-wright how did you get some of those routes? Is there a way we can also look for other routes, so maybe we can contribute to this project.

**Comment by elijah-wright** [comment]
I have a patched version of threads. I just used [Eltion's script](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass) on the threads APK.

**Comment by micheltucker** [comment]
That is pretty cool. Did not know this existed. I'd love to somehow replicate a Twitter Firehose API and then build a bunch of products on top.

**Comment by elijah-wright** [comment]
these endpoints require a very specific UA and an authorization. with "Bearer IG:2:" and then the authorization token. the token is Base64 encoded JSON with your user ID and some session id that idk how to get. so I'll be working on figuring out how the auth workflow works today so I can get that session ID.

**Comment by elijah-wright** [comment]
ok, figured out username password auth. will put it into the library shortly.

**Comment by elijah-wright** [comment]
posting may be a little trickier because you have to supply the upload ID yourself, I'll see what I can do today

**Comment by praharshbhatt** [comment]
@elijah-wright how do we authenticate the user accounts with 2-factor authentication using the `/com.bloks.www.bloks.caa.login.async.send_login_request/` endpoint?
clicking `accept` in the `a device is requesting access` notification and retrying using the same EP (with the same device id) does not seem to work...

**Comment by elijah-wright** [comment]
@praharshbhatt: I don't have 2FA so I couldn't tell you. do you have a patched version of the app?

**Comment by JastinXyz** [comment]
> I have a patched version of threads. I just used [Eltion's script](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass) on the threads APK.

@elijah-wright can you share the patched version that you used?

**Comment by thisisdice** [comment]
Just need and like and follow endpoint and we are flying🦾👀🚀

**Comment by elijah-wright** [comment]
@JastinXyz legally I don't know if I can share it, but if you download a threads APK online, install the dependencies in that repo, and then run the Python script on the APK it should work.

**Comment by elijah-wright** [comment]
@thisisdice both endpoints are in.

**Comment by thisisdice** [comment]
How can we attach media to a post? If i recall from IG theres an upload method to retrieve media ID and then  we use that media ID in the post method

**Comment by elijah-wright** [comment]
@thisisdice take a look at `/rupload_igphoto/`. I'll look at media uploads when I get all the endpoints in.

**Comment by elijah-wright** [comment]
important endpoints have been implemented so I'm closing this now

**Comment by thisisdice** [comment]
@elijah-wright a little out of scope. But any pointers for getting the threads app running. Been having TLS issues.
