### ISSUE TITLE
Make client option object optional

### ISSUE THREAD

**Issue by LilaRest** [threadsjs/threads.js#61]
Hi! Just a tiny bug here.
Your documentation indicates that the options object of the `Client` class is not required, however if I don't pass an empty while instantiating it, I'll get the following Typescript error:
```
Expected 1 arguments, but got 0.ts(2554)
index.d.ts(76, 22): An argument for 'options' was not provided.
```

Btw thanks for this lib :)

**Comment by elijah-wright** [comment]
fixed
