### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by esau-morais** [threadsjs/threads.js#62]
![image](https://github.com/threadsjs/threads.js/assets/55207584/ee27ebc1-0536-42c1-b4f1-cadf60005e4a)

getting [`undefined`](https://github.com/threadsjs/threads.js/blob/main/src/index.js#L159C9-L159C9) in `base` endpoint

**Comment by esau-morais** [comment]
`base: 'https://i.instagram.com',`

**Comment by elijah-wright** [comment]
oh, I see, self is getting lost in the promise. should be fixed in 1.7.3

**Comment by esau-morais** [comment]
thank you, but i receive `undefined` after logging the token
