### ISSUE TITLE
Client instatiated with token isn't working

### ISSUE THREAD

**Issue by LilaRest** [threadsjs/threads.js#64]
Steps to reproduce:
1) Run this piece of code once
```ts
import { Client } from "@threadsjs/threads.js";
import  fs from "fs";
import path from "path";

const tokenPath = path.join(__dirname, "token.json");

const saveToken = (token: string) => {
  fs.writeFileSync(tokenPath, JSON.stringify({ token }));
};

const restoreToken = () => {
  if (!fs.existsSync(tokenPath)) return null;
  const { token } = JSON.parse(fs.readFileSync(tokenPath, "utf-8"));
  return token as string;
};

const main = async () => {
  // Try loading token from disk
  const token = restoreToken();
  console.log(token)

  // Initialize the client and login
  let client: Client;

  // If token was cached, use it
  if (token !== null) client = new Client({ token });
    
  // Else, initiate a new login process
  else {
    client = new Client({});
    await client.login(
      "<username>",
      "<password>"
    );
    saveToken(client.token);
  }

  
  const following = await client.users.following(client.userId);
  console.log(following)
};

main();
```

2) Run it a second time so the client is initiated from the token cached to disk. This outputs the HTML of Instagram "Page not found" page

**Comment by stevenlafl** [comment]
Try running decodeURIComponent() on the token first before passing it in as a token.

**Comment by LilaRest** [comment]
> Try running decodeURIComponent() on the token first before passing it in as a token.

Thanks for this suggestion, it appears to have no effect on the error :|

**Comment by LilaRest** [comment]
I'm using latest version `1.7.2`. Weird thing

**Comment by LilaRest** [comment]
Oh yeah that makes sense. I'll be glad to test it once it's done :)

**Comment by elijah-wright** [comment]
ok, so I figured out what was actually going on. at first I thought it was the tokens but comparing the clients, the one that doesn't work doesn't have client.userId. so for some reason the userId doesn't exist when you use a token. I'll fix it, just give me a minute

**Comment by elijah-wright** [comment]
idk if there is a way to get it without logging in, which is what #32 was about. I'll keep this open in case anyone has any ideas.

**Comment by stevenlafl** [comment]
Well hold on a moment, I am using the token this exact way with 1.7.1. I don't have a problem, why is that?

**Comment by elijah-wright** [comment]
does client.userId exist on your client @stevenlafl?

**Comment by LilaRest** [comment]
Let me know if there anything I can do to help

**Comment by stevenlafl** [comment]
Oh, I'm storing it. Sorry. I suppose if you were to base64 encode a JSON string with the token AND the userid, meant specifically for this app, that would be sufficient.

base64({token, userId}) and then in the app code grab it back out. Our resulting tokens would only be compatible with this implementation, though. And maybe that's fine.

**Comment by stevenlafl** [comment]
```js
import { Client } from "@threadsjs/threads.js";
import  fs from "fs";
import path from "path";

const tokenPath = path.join(__dirname, "token.json");

const saveToken = (token: string, userId: string) => {
  fs.writeFileSync(tokenPath, JSON.stringify({ token, userId }));
};

const restoreToken = () => {
  if (!fs.existsSync(tokenPath)) return null;
  const { token, userId } = JSON.parse(fs.readFileSync(tokenPath, "utf-8"));
  return token as string;
};

const main = async () => {
  // Try loading token from disk
  const token = restoreToken();
  console.log(token)

  // Initialize the client and login
  let client: Client;

  // If token was cached, use it
  if (token !== null) client = new Client({ token });
    
  // Else, initiate a new login process
  else {
    client = new Client({});
    await client.login(
      "<username>",
      "<password>"
    );
    saveToken(client.token, client.userId);
  }

  
  const following = await client.users.following(client.userId);
  console.log(following)
};

main();

```

Like this?

**Comment by LilaRest** [comment]
Thanks @stevenlafl ! But I tried and it doesn't work for me :/
But you talked about base64 and I can't see any usage of base64 in this demonstration

**Comment by elijah-wright** [comment]
on the line where you have "await client.users.following", use userId, not client.usuerId

**Comment by stevenlafl** [comment]
They may need to delete their existing token.json

**Comment by LilaRest** [comment]
Works like a charm, thanks!

**Comment by elijah-wright** [comment]
alr, I'm closing this now
