### ISSUE TITLE
`users.search()` returns wrong number of objects

### ISSUE THREAD

**Issue by LilaRest** [threadsjs/threads.js#66]
Hello again!
I've tried to use `await client.users.search("zuck", 2)` to get 2 results about "zuck" but got tens of objects as response.

Any idea why?

**Comment by elijah-wright** [comment]
yeah, this is a problem I've experienced. I believe the minimum is 30 or 40, so you won't get just 2 responses. nothing I can do about it tho

**Comment by LilaRest** [comment]
Okay thanks for clarification, I think it could be interesting to mention this in the docs :)

**Comment by elijah-wright** [comment]
fixed
