### ISSUE TITLE
Can't succeed to like a post

### ISSUE THREAD

**Issue by LilaRest** [threadsjs/threads.js#69]
Hi! Anyone here have suceeded to like a post?
I currently use `await sideClient.posts.like(postId, userToEngage.userId)`, it doesn't throw an error but then I cannot see likes on the Threads app

**Comment by stevenlafl** [comment]
> Hi! Anyone here have suceeded to like a post?
> I currently use `await sideClient.posts.like(postId, userToEngage.userId)`, it doesn't throw an error but then I cannot see likes on the Threads app

Instead of passing the user's Id, pass your own. Also simply "1" works.

**Comment by elijah-wright** [comment]
looks to be resolved, if there are any issues reopen this
