### ISSUE TITLE
Fetch without authentication

### ISSUE THREAD

**Issue by sulaimanwebdev** [threadsjs/threads.js#70]
Can we fetch Threads data without authentication based on user ID? Data like Thread content likes replies. 
This doesn't include posting and other functionalities that requires authentication

**Comment by elijah-wright** [comment]
technically yes, using GraphQL. but using the app itself, those endpoints are authenticated.

**Comment by micheltucker** [comment]
Would actually be a nice addition to use GraphQL for unauthenticated users. We had these endpoints in the beginning. @sulaimanwebdev would be a cool addition to the repo.

**Comment by elijah-wright** [comment]
I could add a graphql manager. I'll work on this in the morning

**Comment by stevenlafl** [comment]
That would actually be super neat - I could have a logged-out view in the app.  This is proving to be quite the exercise.

**Comment by sulaimanwebdev** [comment]
It would be amazing to see posts for unauthenticated users just like we can see Threads on Web

**Comment by sulaimanwebdev** [comment]
> added in 1.8.1

Hi, can you please add "get unauthenticated" data in the readme?
