### ISSUE TITLE
Proxy Implementation

### ISSUE THREAD

**Issue by sooluh** [threadsjs/threads.js#74]
I noticed on #71 there are some issues regarding Instagram blocking IP addresses, and I think implementing a proxy on the HTTP agent being used might help. I'm not sure if [undici](https://github.com/threadsjs/threads.js/blob/main/src/managers/RESTManager.js#L1) supports proxies or not, but what I do know is that some other HTTP agents like [axios](https://github.com/axios/axios) support it.

**Comment by elijah-wright** [comment]
do you want to do this by adding the base to the client options?

**Comment by sooluh** [comment]
I think that's the only thing that is possible

**Comment by elijah-wright** [comment]
fixed

**Comment by stevenlafl** [comment]
Unfortunately, whatever is new completely breaks the API for me, so I can't use the new version. I am of course using TypeScript.

Passing the token results in getting an HTML page back.

**Comment by sooluh** [comment]
Please try using the older version; it seems to be the same. I feel there have been recent changes to the Instagram endpoint, and I've also noticed it.

**Comment by stevenlafl** [comment]
The old version works, I still use it.
