### ISSUE TITLE
User agent mismatch.

### ISSUE THREAD

**Issue by sleep9** [threadsjs/threads.js#76]
await client.users.fetch(25025320).then(user => {
		console.log(user);
});
resulting in
{"message": "useragent mismatch", "status": "fail"}

I set the client user agent to the following https://www.whatismybrowser.com/detect/what-is-my-user-agent/
attempted my desktop as well as the simulator user agent.

**Comment by sleep9** [comment]
Resolved by using 'Instagram 219.0.0.12.117 Android' useragent and a fresh appid

**Comment by elijah-wright** [comment]
could you provide those?

**Comment by elijah-wright** [comment]
no longer applicable in v2
