### ISSUE TITLE
Login credentials / 2FA

### ISSUE THREAD

**Issue by sleep9** [threadsjs/threads.js#78]
How to utilize 2FA / checkpoint challenge code for login? Does not seem to be documented. I have an app implementing this library but is being rejected due to login rejections from Instagram. I am looking for a way one can authorize the login via instagram for my third party client.

**Comment by elijah-wright** [comment]
do you have 2FA on your account? the console should prompt you to put in your code.

**Comment by sleep9** [comment]
It doesnt prompt. I removed the following dependency 
`const { fetch } = require("undici");`
for regular fetch library so that it would work on react-native. Could that be the source of the lack of 2fa in my build?

**Comment by elijah-wright** [comment]
interesting, I'm also working with the Instagram API with React Native (but not using threads.js). are you getting any login requests?

**Comment by sleep9** [comment]
What do you mean by login requests. If I try to login I get a failed login and a prompt in instagram telling me their was a login attempt. Only if I flag "this was me" will any subsequent logins from my app work. If 2FA is on what is supposed to occur?

**Comment by elijah-wright** [comment]
ah ok, this makes more sense now. if what's making the request to Instagram has a different IP than what your home network is, you'll get that popup. so, for example, if I have an Express "proxy" server running on Vercel's servers and I try to make a request, it'll go through Vercel's servers and you'll have to do the login attempt thing. there's really nothing I can do about this unfortunately but I can try and see if there's some way to use a preexisting device to make that request back telling Instagram that IP is ok

**Comment by elijah-wright** [comment]
no longer applicable in v2
