### ISSUE TITLE
official API support

### ISSUE THREAD

**Issue by elijah-wright** [threadsjs/threads.js#81]
https://www.threads.net/@0xjessel/post/C1AqVMiySi6

issue to keep track of endpoints in the upcoming official API

**Comment by sleep9** [comment]
https://developers.facebook.com/docs/threads

Any plans to support this?

**Comment by elijah-wright** [comment]
thanks for showing me this, will refactor ASAP

**Comment by elijah-wright** [comment]
@sleep9 the API you linked is in private beta, meaning I don't have the ability to test it in practicality. however, I'm preparing for the public release of the API and I'm setting up a branch (v2) for anyone who does have access to the API to use. when the API releases to the public, I will merge that branch into this one

**Comment by sleep9** [comment]
Great news. Looking forward.

**Comment by elijah-wright** [comment]
the official API has been released. I am closing this and publishing my changes immediately

**Comment by sleep9** [comment]
Have the changes been merged already? I noticed most of the functionality is gone.

**Comment by elijah-wright** [comment]
yes, unfortunately there's not a lot to the Threads API at the moment. you can still use v1.9.0 if you want to use the old library functions. is there anything you need in specific?

**Comment by sleep9** [comment]
Almost every endpoint is utilized. Will have maintain our own library that is a combination of the new and old libraries. Reviewing the code I am unsure which functions we can migrate to the new functions and which ones we need to maintain as documentation is lacking. Do you know where I can find the official API spec? Also do you know where I can find documentation on logging into threads using Instagrams oauth/2fa?

**Comment by elijah-wright** [comment]
I would recommend not switching to v2 then. the Threads API documentation is [here](https://developers.facebook.com/docs/threads) but it is very unfinished and references some endpoints that have a different structure than others. still, it has information on using Threads with an OAuth application

**Comment by sleep9** [comment]
Is it possible to initialize v1.9.0 with an access token retrieved via threads oauth? Right now we are using the client.login method to authenticate...

**Comment by elijah-wright** [comment]
as far as I know, no, because they're different endpoints (graph.threads.net/graph.instagram.com vs i.instagram.com). from what I know about Instagram, the split is intentional in order to prevent people from using official Meta APIs to create third-party apps

**Comment by sleep9** [comment]
Yea thats unfortunate. While using v1.9.0 logins are frequently rejected which is a dealbreaker for a production app and the new threads API only supports a subset of the previous functionality.
