### ISSUE TITLE
Tokens are not a constant length.

### ISSUE THREAD

**Issue by Mastriel** [threadsjs/threads.js#9]
`getToken()` grabs a token of a length of 160 characters from the response, however it seems that not all tokens are a constant length. My token is 164 characters for instance, apparently. Using an incomplete token can cause some issues, as you'd imagine.

**Comment by elijah-wright** [comment]
does your token end in ==, by any chance?

**Comment by Mastriel** [comment]
It does, but that's cut off when using `getToken`. I think that it's because "ds_user_id" in the decoded json contains your Instagram/Threads ID, which is a variable length.

**Comment by elijah-wright** [comment]
fix should work but my threads account got locked for logging in and out too many times so I can't test it
